(function(g){var window=this;var Ipa=function(a,b){return g.Wb(a,b)},e5=function(a,b,c){a.l.set(b,c)},f5=function(a){e5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.A)()).toString(36));
return a},g5=function(a,b,c){g.La(c)||(c=[String(c)]);
g.Vm(a.l,b,c)},Jpa=function(a,b){var c=[];
g.Zi(b,function(d){try{var e=g.Fn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.En(e)&&c.push(d)},a);
return c},Kpa=function(a,b){var c=Jpa(a,b);
(0,g.z)(c,function(d){g.Fn.prototype.remove.call(this,d)},a)},h5=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},Lpa=function(a,b){g.ab(a,b)||a.push(b)},i5=function(a){var b=0,c;
for(c in a)b++;return b},j5=function(a,b){var c=b instanceof g.xc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},k5=function(){},Mpa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Npa=function(a){if(a.wd&&"function"==typeof a.wd)return a.wd();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Sb(a)},Opa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)(0,g.z)(a,b,void 0);else{if(a.Yd&&"function"==typeof a.Yd)var c=a.Yd();else if(a.wd&&"function"==typeof a.wd)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Tb(a);d=Npa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Ppa=function(a,b,c,d){var e=new g.Jm(null,void 0);
a&&g.Km(e,a);b&&g.Lm(e,b);c&&g.Mm(e,c);d&&(e.i=d);return e},l5=function(a,b){g.Ho[a]=!0;
var c=g.Fo();c&&c.publish.apply(c,arguments);g.Ho[a]=!1},m5=function(a){try{var b=(0,g.$x)(),c=(0,g.Zx)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Qpa=function(){var a=(0,g.Zx)();
a&&Kpa(a,a.g.df(!0))},n5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Gm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Rpa(this,a.capabilities||""),Spa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Rpa=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Ra(Ipa,Tpa)).forEach(function(c){a.capabilities.add(c)})},Spa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},o5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},q5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Upa=function(a){return new o5(a)},r5=function(a){return g.La(a)?(0,g.fe)(a,Upa):[]},s5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},t5=function(a){return g.La(a)?"["+(0,g.fe)(a,s5).join(",")+"]":"null"},u5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Vpa=function(a){return(0,g.fe)(a,function(b){return{key:b.id,
name:b.name}})},v5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},w5=function(a,b){return g.Ya(a,function(c){return p5(c,b)})},x5=function(){var a=g.by("yt-remote-connected-devices")||[];
g.rb(a);return a},Wpa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.fe)(a,function(d,e){return 0==e?d:d.substring(c.length)})},y5=function(a){g.ay("yt-remote-connected-devices",a,86400)},A5=function(){if(z5)return z5;
var a=g.by("yt-remote-device-id");a||(a=u5(),g.ay("yt-remote-device-id",a,31536E3));for(var b=x5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return z5=d},B5=function(){var a=x5(),b=A5();
g.ab(a,b);g.jL()&&g.ub(a,b);a=Wpa(a);if(g.bb(a))try{g.ur("remote_sid")}catch(c){}else try{g.tr("remote_sid",a.join(","),-1)}catch(c){}},C5=function(){return g.by("yt-remote-session-browser-channel")},D5=function(){return g.by("yt-remote-local-screens")||[]},E5=function(){g.ay("yt-remote-lounge-token-expiration",!0,86400)},Xpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.fe)(D5(),function(d){return d.loungeToken}),c=(0,g.fe)(a,function(d){return d.loungeToken});
(0,g.Yg)(c,function(d){return!g.ab(b,d)})&&E5();
g.ay("yt-remote-local-screens",a,31536E3)},Ypa=function(a,b){g.ay("yt-remote-session-browser-channel",a);
g.ay("yt-remote-session-screen-id",b);var c=x5(),d=A5();g.ab(c,d)||c.push(d);y5(c);B5()},F5=function(a){a||(m5("yt-remote-session-screen-id"),m5("yt-remote-session-video-id"));
B5();a=x5();g.eb(a,A5());y5(a)},H5=function(){if(!G5){var a=g.Pn();
a&&(G5=new g.zn(a))}return G5?!!G5.get("yt-remote-use-staging-server"):!1},I5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},J5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},L5=function(a){a.length?K5(a.shift(),function(){L5(a)}):M5()},Zpa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},K5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},M5=function(){var a=J5();
a&&a(!1,"No cast extension found")},N5=function(){if($pa){var a=2,b=J5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;K5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",M5,c)}},aqa=function(){N5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);L5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},O5=function(a,b,c){g.E.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Tc=b;this.u=(0,g.x)(this.ZB,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},P5=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Mpa(a)},Q5=function(){},R5=function(){},S5=function(){},U5=function(a){return(a=T5(a))?new ActiveXObject(a):new XMLHttpRequest},T5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},V5=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.w=d||1;this.o=45E3;this.ba=new g.sZ(this);this.i=new g.gl;this.i.setInterval(250)},X5=function(a,b,c){a.Lh=1;
a.Lf=f5(b.clone());a.fh=c;a.u=!0;W5(a,null)},Y5=function(a,b,c,d,e){a.Lh=1;
a.Lf=f5(b.clone());a.fh=null;a.u=c;e&&(a.dz=!1);W5(a,d)},W5=function(a,b){a.si=(0,g.A)();
Z5(a);a.qg=a.Lf.clone();g5(a.qg,"t",a.w);a.Gk=0;a.uc=a.g.To(a.g.uk()?b:null);0<a.zp&&(a.kn=new g.jl((0,g.x)(a.bA,a,a.uc),a.zp));a.ba.ea(a.uc,"readystatechange",a.TK);var c=a.Mg?g.bc(a.Mg):{};a.fh?(a.Pn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.uc.send(a.qg,a.Pn,a.fh,c)):(a.Pn="GET",a.dz&&!g.Ld&&(c.Connection="close"),a.uc.send(a.qg,a.Pn,null,c));a.g.ne(1)},f6=function(a,b,c){for(var d=!0;!a.Ag&&a.Gk<c.length;){var e=bqa(a,c);
if(e==$5){4==b&&(a.ag=4,a6(15),d=!1);break}else if(e==b6){a.ag=4;a6(16);d=!1;break}else c6(a,e)}4==b&&0==c.length&&(a.ag=1,a6(17),d=!1);a.oe=a.oe&&d;d||(d6(a),e6(a))},bqa=function(a,b){var c=a.Gk,d=b.indexOf("\n",c);
if(-1==d)return $5;c=Number(b.substring(c,d));if(isNaN(c))return b6;d+=1;if(d+c>b.length)return $5;var e=b.substr(d,c);a.Gk=d+c;return e},i6=function(a,b){a.si=(0,g.A)();
Z5(a);var c=b?window.location.hostname:"";a.qg=a.Lf.clone();e5(a.qg,"DOMAIN",c);e5(a.qg,"t",a.w);try{a.ue=new ActiveXObject("htmlfile")}catch(n){d6(a);a.ag=7;a6(22);e6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in g6)k=g6[l];else if(l in h6)k=g6[l]=h6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
g6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.ue.open();a.ue.write(g.Mc(c));a.ue.close();a.ue.parentWindow.m=(0,g.x)(a.jK,a);a.ue.parentWindow.d=(0,g.x)(a.ly,a,!0);a.ue.parentWindow.rpcClose=(0,g.x)(a.ly,a,!1);c=a.ue.createElement("DIV");a.ue.parentWindow.document.body.appendChild(c);d=g.Bc(a.qg.toString());d=g.Zc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.ne(1)},Z5=function(a){a.ls=(0,g.A)()+a.o;
j6(a,a.o)},j6=function(a,b){if(null!=a.Hi)throw Error("WatchDog timer not null");
a.Hi=k6((0,g.x)(a.rK,a),b)},l6=function(a){a.Hi&&(g.u.clearTimeout(a.Hi),a.Hi=null)},e6=function(a){a.g.dv()||a.Ag||a.g.an(a)},d6=function(a){l6(a);
g.Ci(a.kn);a.kn=null;a.i.stop();g.uZ(a.ba);if(a.uc){var b=a.uc;a.uc=null;b.abort();b.dispose()}a.ue&&(a.ue=null)},c6=function(a,b){try{a.g.fy(a,b),a.g.ne(4)}catch(c){}},n6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;m6(a,b,function(k){k?c(!0):g.u.setTimeout(function(){n6(a,b,c,d,f)},f)})}},m6=function(a,b,c){var d=new Image;
d.onload=function(){try{o6(d),c(!0)}catch(e){}};
d.onerror=function(){try{o6(d),c(!1)}catch(e){}};
d.onabort=function(){try{o6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{o6(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
j5(d,a)},o6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},p6=function(a){this.g=a;
this.i=new Q5},r6=function(a){var b=q6(a.g,a.Ri,"/mail/images/cleardot.gif");
f5(b);n6(b.toString(),5E3,(0,g.x)(a.fB,a),3,2E3);a.ne(1)},t6=function(a){var b=a.g.D;
if(null!=b)a6(5),b?(a6(11),s6(a.g,a,!1)):(a6(12),s6(a.g,a,!0));else if(a.Ad=new V5(a,void 0,void 0,void 0),a.Ad.Mg=a.xp,b=a.g,b=q6(b,b.uk()?a.tj:null,a.yp),a6(5),!g.Jd||g.nd(10))g5(b,"TYPE","xmlhttp"),Y5(a.Ad,b,!1,a.tj,!1);else{g5(b,"TYPE","html");var c=a.Ad;a=!!a.tj;c.Lh=3;c.Lf=f5(b.clone());i6(c,a)}},u6=function(a){g.wk.call(this);
this.headers=new g.Gm;this.M=a||null;this.l=!1;this.R=this.g=null;this.W=this.D="";this.w=0;this.o="";this.u=this.aa=this.C=this.P=!1;this.B=0;this.G=null;this.X="";this.I=this.S=!1},cqa=function(a){return g.Jd&&g.ld(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},dqa=function(a){return"content-type"==a.toLowerCase()},x6=function(a,b){a.l=!1;
a.g&&(a.u=!0,a.g.abort(),a.u=!1);a.o=b;a.w=5;v6(a);w6(a)},v6=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},A6=function(a){if(a.l&&"undefined"!=typeof g.yZ)if(a.R[1]&&4==y6(a)&&2==a.getStatus())z6(a,"Local request error detected and ignored");
else if(a.C&&4==y6(a))g.hl(a.fv,0,a);else if(a.dispatchEvent("readystatechange"),4==y6(a)){z6(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.uf(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!eqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.w=6;try{var l=2<y6(a)?a.g.statusText:""}catch(m){l=""}a.o=l+" ["+a.getStatus()+"]";v6(a)}}finally{w6(a)}}},w6=function(a,b){if(a.g){B6(a);
var c=a.g,d=a.R[0]?g.Ia:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},B6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.G&&(g.u.clearTimeout(a.G),a.G=null)},y6=function(a){return a.g?a.g.readyState:0},C6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},z6=function(a,b){return b+" ["+a.W+" "+a.D+" "+a.getStatus()+"]"},D6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new Q5;this.C=a||null;this.D=null!=b?b:null;this.w=c||!1},fqa=function(a,b){this.g=a;
this.map=b;this.context=null},E6=function(a){g.Zj.call(this,"statevent",a)},F6=function(a,b){g.Zj.call(this,"timingevent",a);
this.size=b},G6=function(a){g.Zj.call(this,"serverreachability",a)},K6=function(a){H6(a);
if(3==a.g){var b=a.Yj++,c=a.Jl.clone();e5(c,"SID",a.l);e5(c,"RID",b);e5(c,"TYPE","terminate");I6(a,c);b=new V5(a,a.l,b,void 0);b.Lh=2;b.Lf=f5(c.clone());j5(new Image,b.Lf.toString());b.si=(0,g.A)();Z5(b)}J6(a)},M6=function(a){a.zB(1,0);
a.Jl=q6(a,null,a.wp);L6(a)},H6=function(a){a.Qf&&(a.Qf.abort(),a.Qf=null);
a.Qb&&(a.Qb.cancel(),a.Qb=null);a.ff&&(g.u.clearTimeout(a.ff),a.ff=null);N6(a);a.td&&(a.td.cancel(),a.td=null);a.Wf&&(g.u.clearTimeout(a.Wf),a.Wf=null)},O6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new fqa(a.yG++,b));2!=a.g&&3!=a.g||L6(a)},L6=function(a){a.td||a.Wf||(a.Wf=k6((0,g.x)(a.ky,a),0),a.Eh=0)},R6=function(a,b){if(1==a.g){if(!b){a.Yj=Math.floor(1E5*Math.random());
var c=a.Yj++,d=new V5(a,"",c,void 0);d.Mg=null;var e=P6(a),f=a.Jl.clone();e5(f,"RID",c);e5(f,"CVER","1");I6(a,f);X5(d,f,e);a.td=d;a.g=2}}else 3==a.g&&(b?Q6(a,b):0==a.i.length||a.td||Q6(a))},Q6=function(a,b){if(b)if(6<a.Bg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Yj-1;var d=P6(a)}else c=b.B,d=b.fh;else c=a.Yj++,d=P6(a);var e=a.Jl.clone();e5(e,"SID",a.l);e5(e,"RID",c);e5(e,"AID",a.Yh);I6(a,e);c=new V5(a,a.l,c,a.Eh+1);c.Mg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.td=c;X5(c,e,d)},I6=function(a,b){if(a.Qc){var c=a.Qc.Fu();
c&&g.Mb(c,function(d,e){e5(b,e,d)})}},P6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Bg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Bg?e:f-d;try{g.Mb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},S6=function(a){a.Qb||a.ff||(a.B=1,a.ff=k6((0,g.x)(a.jy,a),0),a.yh=0)},U6=function(a){if(a.Qb||a.ff||3<=a.yh)return!1;
a.B++;a.ff=k6((0,g.x)(a.jy,a),T6(a,a.yh));a.yh++;return!0},s6=function(a,b,c){a.Nn=c;
a.Ae=b.sf;a.w||M6(a)},N6=function(a){null!=a.Fg&&(g.u.clearTimeout(a.Fg),a.Fg=null)},T6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.Qc&&(c=null);var d=(0,g.x)(a.AL,a);c||(c=new g.Jm("//www.google.com/images/cleardot.gif"),f5(c));m6(c.toString(),1E4,d)}else a6(2);V6(a,b)},V6=function(a,b){a.g=0;
a.Qc&&a.Qc.Qt(b);J6(a);H6(a)},J6=function(a){a.g=0;
a.Ae=-1;if(a.Qc)if(0==a.o.length&&0==a.i.length)a.Qc.Mo();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Qc.Mo(b)}},q6=function(a,b,c){var d=g.Rm(c);
if(""!=d.g)b&&g.Lm(d,b+"."+d.g),g.Mm(d,d.u);else{var e=window.location;d=Ppa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.dj&&g.Mb(a.dj,function(f,k){e5(d,k,f)});
e5(d,"VER",a.Bg);I6(a,d);return d},k6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},a6=function(a){X6.dispatchEvent(new E6(X6,a))},Y6=function(){},Z6=function(){this.g=[];
this.i=[]},gqa=function(a,b){this.action=a;
this.params=b||{}},$6=function(a,b){g.E.call(this);
this.g=new g.I(this.aK,0,this);g.H(this,this.g);this.Tc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},a7=function(a,b,c){this.G=a;
this.w=b;this.l=new g.yn;this.i=new $6(this.dL,this);this.g=null;this.bb=!1;this.u=null;this.D="";this.C=this.o=0;this.B=[];this.I=c||!1},hqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Nn,sessionId:a.g.l,arrayId:a.g.Yh}},b7=function(a,b){a.C=b||0;
a.i.stop();a.g&&(3==a.g.g&&R6(a.g),K6(a.g));a.C=0},c7=function(a){return!!a.g&&3==a.g.g},iqa=function(a,b){(a.w.loungeIdToken=b)||a.i.stop()},d7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.uf(4,a))||"";b&&(this.port=":"+b);this.domain=g.vf(a)||"";a=g.Kb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Jb(a,"10.0")&&(this.i=!1))},e7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ff(c+b,{})},f7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),Nd:g.Ra(a.u,e)};c&&(a.sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ap(b,a)},jqa=function(){var a=g7;
h7();i7.push(a);j7(i7)},k7=function(a,b){h7();
var c=i7,d=kqa(a,String(b));g.bb(c)?lqa(d):(j7(c),(0,g.z)(c,function(e){e(d)}))},h7=function(){i7||(i7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",i7,void 0))},lqa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},j7=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},kqa=function(a,b){var c=((0,g.A)()-mqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.O.call(this);
this.B=a;this.g=[]},p7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},nqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Wd)(a.g,function(f){return!!v5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=p7(a,b[d])||c;return c},oqa=function(a,b){var c=a.g.length;
a.g=(0,g.Wd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},q7=function(a,b,c,d){g.O.call(this);
this.w=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},s7=function(a){o7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;r7(this);this.info("Initializing with "+t5(this.g))},t7=function(a){if(a.g.length){var b=(0,g.fe)(a.g,function(d){return d.id}),c=e7(a.l,"/pairing/get_lounge_token_batch");
f7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.jC,a),(0,g.x)(a.iC,a))}},r7=function(a){var b=r5(D5());
b=(0,g.Wd)(b,function(c){return!c.uuid});
return nqa(a,b)},u7=function(a,b){Xpa((0,g.fe)(a.g,q5));
b&&E5()},w7=function(a,b){g.O.call(this);
this.w=b;var c=g.by("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.w(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;v7("Initialized with "+g.zj(this.g))},x7=function(a,b,c){var d=e7(a.u,"/pairing/get_screen_availability");
f7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},y7=function(a,b){a:if(i5(b)!=i5(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(v7("Updated online screens: "+g.zj(a.g)),a.g=b,a.N("screenChange"));pqa(a)},z7=function(a){isNaN(a.l)||g.Eo(a.l);
a.l=g.Co((0,g.x)(a.vr,a),0<a.o&&a.o<(0,g.A)()?2E4:1E4)},v7=function(a){k7("OnlineScreenService",a)},A7=function(a){var b={};
(0,g.z)(a.w(),function(c){c.token?b[c.token]=c.id:this.Kb("Requesting availability of screen w/o lounge token.")});
return b},pqa=function(a){a=g.Tb(g.Nb(a.g,function(b){return b}));
g.rb(a);a.length?g.ay("yt-remote-online-screen-ids",a.join(","),60):m5("yt-remote-online-screen-ids")},B7=function(a){o7.call(this,"ScreenService");
this.w=a;this.i=this.l=null;this.o=[];this.u={};qqa(this)},D7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Kd();if(k=(c?w5(k,c):null)||w5(k,b)){k.uuid=b;var l=C7(a,k);x7(a.i,l,function(m){e(m?l:null)})}else c?rqa(a,c,(0,g.x)(function(m){var n=C7(this,new o5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));x7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},E7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},rqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Ap(e7(a.w,"/pairing/get_lounge_token_batch"),e)},F7=function(a){a.g=a.l.Kd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+t5(a.g))},qqa=function(a){G7(a);
a.l=new s7(a.w);a.l.subscribe("screenChange",(0,g.x)(a.qC,a));F7(a);a.o=r5(g.by("yt-remote-automatic-screen-cache")||[]);G7(a);a.info("Initializing automatic screens: "+t5(a.o));a.i=new w7(a.w,(0,g.x)(a.Kd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},C7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=w5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ay("yt-remote-automatic-screen-cache",(0,g.fe)(a.o,q5)));G7(a);a.u[b.uuid]=b.id;g.ay("yt-remote-device-id-map",a.u,31536E3);return b},G7=function(a){a.u=g.by("yt-remote-device-id-map")||{}},H7=function(a,b,c){g.O.call(this);
this.R=c;this.D=a;this.i=b;this.l=null},I7=function(a,b){k7(a.R,b)},K7=function(a,b){H7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.w=(0,g.x)(this.gM,this);this.u=(0,g.x)(this.CK,this);this.o=g.Co((0,g.x)(function(){J7(this,null)},this),12E4)},sqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.zj(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){I7(this,"Failed to send message: getMdxSessionStatus.")},a)):I7(a,"Sending yt message without session: "+g.zj(b))},J7=function(a,b){g.Eo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.cn,a),d=(0,g.x)(a.Md,a);a.Yu(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},L7=function(a,b,c){H7.call(this,a,b,"DialSession");
this.o=this.C=null;this.G="";this.M=c;this.u=null;this.B=g.Ia;this.w=NaN;this.I=(0,g.x)(this.jM,this);this.g=g.Ia},M7=function(a){a.g=a.D.hA(a.G,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ia;
this.cn(b)},a),(0,g.x)(function(b){this.g=g.Ia;
this.Md(b)},a))},N7=function(a){var b={};
b.pairingCode=a.G;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}H5()&&(b.env_useStageMdx=1);return g.Cf(b)},O7=function(a,b){H7.call(this,a,b,"ManualSession");
this.g=g.Co((0,g.x)(this.Zh,this,null),150)},P7=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.w=c||"cl";this.C=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.jJ,this)},Q7=function(a,b){return b?g.Ya(a.l,function(c){return p5(b,c.label)},a):null},R7=function(a){k7("Controller",a)},g7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},S7=function(a){return a.u||!!a.l.length||!!a.g},T7=function(a,b,c){b!=a.g&&(g.Ci(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.iy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.Zh(null)):a.N("yt-remote-cast2-session-change",null))},U7=function(a){var b=a.i.gA(),c=a.g&&a.g.i;
a=(0,g.fe)(b,function(d){c&&p5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Q7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},wqa=function(a,b,c,d,e,f,k){tqa()?uqa(b,e,f,k)&&(W7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?X7(a,c):(window.__onGCastApiAvailable=function(l,m){l?X7(a,c):(Y7("Failed to load cast API: "+m),Z7(!1),W7(!1),m5("yt-remote-cast-available"),m5("yt-remote-cast-receiver"),$7(),c(!1))},d?g.Po("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?aqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?M5():(N5(),L5(vqa.map(Zpa))))):V7("Cannot initialize because not running Chrome")},$7=function(){V7("dispose");
var a=a8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);b8(!1);g.Ko(c8);c8.length=0},d8=function(){return!!g.by("yt-remote-cast-installed")},e8=function(){var a=g.by("yt-remote-cast-receiver");
return a?a.friendlyName:null},f8=function(){V7("clearCurrentReceiver");
m5("yt-remote-cast-receiver")},g8=function(){return d8()?a8()?a8().getCastSession():(Y7("getCastSelector: Cast is not initialized."),null):(Y7("getCastSelector: Cast API is not installed!"),null)},i8=function(){d8()?a8()?h8()?(V7("Requesting cast selector."),a8().requestSession()):(V7("Wait for cast API to be ready to request the session."),c8.push(g.Jo("yt-remote-cast2-api-ready",i8))):Y7("requestCastSelector: Cast is not initialized."):Y7("requestCastSelector: Cast API is not installed!")},j8=function(a,
b){h8()?a8().setConnectedScreenStatus(a,b):Y7("setConnectedScreenStatus called before ready.")},tqa=function(){var a=0<=g.Kb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Js||a},xqa=function(a,b){a8().init(a,b)},uqa=function(a,b,c,d){var e=!1;
a8()||(a=new P7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ay("yt-remote-cast-available",f);l5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){V7("onReceiverSelected: "+f.friendlyName);
g.ay("yt-remote-cast-receiver",f);l5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){V7("onReceiverResumed: "+f.friendlyName);
g.ay("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){V7("onSessionChange: "+s5(f));
f||m5("yt-remote-cast-receiver");l5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
V7("cloudview.createSingleton_: "+e);return e},a8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},X7=function(a,b){Z7(!0);
W7(!1);xqa(a,function(c){c?(b8(!0),g.Mo("yt-remote-cast2-api-ready")):(Y7("Failed to initialize cast API."),Z7(!1),m5("yt-remote-cast-available"),m5("yt-remote-cast-receiver"),$7());b(c)})},V7=function(a){k7("cloudview",a)},Y7=function(a){k7("cloudview",a)},Z7=function(a){V7("setCastInstalled_ "+a);
g.ay("yt-remote-cast-installed",a)},h8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},b8=function(a){V7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},W7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},k8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.w=this.B=0;this.g=null;this.hasNext=this.Be=!1;this.D=this.C=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},l8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Be=!1;a.hasNext=!1;a.B=0;a.w=(0,g.A)();a.o=0;a.i=0;a.C=0;a.D=0;a.l=NaN;a.u=!1},m8=function(a){return 1==a.playerState?((0,g.A)()-a.w)/1E3:0},n8=function(a,b){a.B=b;
a.w=(0,g.A)()},o8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.A)()-a.w)/1E3+a.B;
case -1E3:return 0}return a.B},p8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&l8(a)},q8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Be;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.w;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.D;b.liveIngestionTime=a.l;return b},t8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.w=[];this.u=new Z6;this.l=this.i=null;this.D=(0,g.x)(this.gH,this);this.B=(0,g.x)(this.bk,this);this.C=(0,g.x)(this.fH,this);this.G=(0,g.x)(this.sH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.rs,this),r8(this))):c=3;0!=c&&(b?this.rs(c):g.Co((0,g.x)(function(){this.rs(c)},this),0));
var d=g8();d&&s8(this,d);this.subscribe("yt-remote-cast2-session-change",this.G)},u8=function(a){return new k8(a.o.getPlayerContextData())},r8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.w.push(this.o.subscribe(b,g.Ra(this.gJ,b),this))},a)},v8=function(a){(0,g.z)(a.w,function(b){this.o.unsubscribeByKey(b)},a);
a.w.length=0},w8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},y8=function(a,b,c){var d=u8(a);
n8(d,c);-1E3!=d.playerState&&(d.playerState=b);x8(a,d)},z8=function(a,b,c){a.o.sendMessage(b,c)},x8=function(a,b){v8(a);
a.o.setPlayerContextData(q8(b));r8(a)},s8=function(a,b){a.l&&(a.l.removeUpdateListener(a.D),a.l.removeMediaListener(a.B),a.bk(null));
a.l=b;a.l&&(k7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.D),a.l.addMediaListener(a.B),a.l.media.length&&a.bk(a.l.media[0]))},A8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=u8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;n8(d,a.i.getEstimatedTime());x8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.x)(function(d){this.Kb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kb("Retrying "+b+" using MDx browser channel."),z8(this,b,c))},a)},C8=function(a,b,c){g.O.call(this);
this.u=NaN;this.I=!1;this.C=this.B=this.D=this.G=NaN;this.R=[];this.o=this.w=this.l=this.Na=this.g=null;this.P=a;this.R.push(g.Zq(window,"beforeunload",(0,g.x)(this.cC,this)));this.i=[];this.Na=new k8;this.M=b.id;this.g=yqa(this,c);this.g.subscribe("handlerOpened",this.kH,this);this.g.subscribe("handlerClosed",this.hH,this);this.g.subscribe("handlerError",this.iH,this);this.g.subscribe("handlerMessage",this.jH,this);iqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Na.videoId;
g.jL()&&g.ay("yt-remote-session-video-id",d)},this)},D8=function(a){k7("conn",a)},yqa=function(a,b){return new a7(e7(a.P,"/bc"),b)},E8=function(a,b){a.N("proxyStateChange",b)},zqa=function(a){a.u=g.Co((0,g.x)(function(){D8("Connecting timeout");
this.Ch(1)},a),2E4)},F8=function(a){g.Eo(a.u);
a.u=NaN},G8=function(a){g.Eo(a.G);
a.G=NaN},Aqa=function(a){H8(a);
a.D=g.Co((0,g.x)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.Eo(a.D);
a.D=NaN},K8=function(a,b){b&&(F8(a),G8(a));
b==(c7(a.g)&&isNaN(a.u))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.Wu()&&a.Na.reset(),E8(a,1),I8(a,"getNowPlaying"),J8(a)):a.Ch(1)},Bqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Na.videoId&&(g.Zb(b.params)?a.Na.g=null:a.Na.g=b.params,a.N("remotePlayerChange"))},L8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Na.listId=b.params.listId||a.Na.listId;p8(a.Na,c,d);a.N("remoteQueueChange")},Cqa=function(a,b){b.params=b.params||{};
L8(a,b);M8(a,b);a.N("autoplayDismissed")},M8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
n8(a.Na,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Na.playerState&&(c=-1E3);a.Na.playerState=c;c=Number(b.params.loadedTime);a.Na.D=isNaN(c)?0:c;c=Number(b.params.duration);a.Na.C=isNaN(c)?0:c;c=a.Na;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Na;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Na.playerState?Aqa(a):H8(a);a.N("remotePlayerChange")},Dqa=function(a,b){if(-1E3!=
a.Na.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Na.playerState=c;c=parseInt(b.params.currentTime,10);n8(a.Na,isNaN(c)?0:c);a.N("remotePlayerChange")}},Eqa=function(a,b){var c="true"==b.params.muted;
a.Na.volume=parseInt(b.params.volume,10);a.Na.muted=c;a.N("remotePlayerChange")},Fqa=function(a,b){a.w=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Gqa=function(a,b){var c="true"==b.params.hasNext;
a.Na.Be="true"==b.params.hasPrevious;a.Na.hasNext=c;a.N("previousNextChange")},J8=function(a){g.Eo(a.C);
a.C=g.Co((0,g.x)(a.Ch,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.zj(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},N8=function(a){o7.call(this,"ScreenServiceProxy");
this.Sc=a;this.i=[];this.i.push(this.Sc.$_s("screenChange",(0,g.x)(this.eM,this)));this.i.push(this.Sc.$_s("onlineScreenChange",(0,g.x)(this.JI,this)))},Lqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.uo("MDX_CONFIG")||b;Qpa();B5();O8||(O8=new d7(b?b.loungeApiHost:void 0),H5()&&(O8.g="/api/loungedev"));P8||(P8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",P8,void 0));Hqa();var c=Q8();if(!c){var d=new B7(O8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=Q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);wqa(a,d,function(m){m?R8()&&j8(R8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){l5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),S8("Initializing: "+g.zj(b)),T8.push(g.Jo("yt-remote-cast2-availability-change",function(){l5("yt-remote-receiver-availability-change")})),T8.push(g.Jo("yt-remote-cast2-receiver-selected",function(){U8(null);
l5("yt-remote-auto-connect","cast-selector-receiver")})),T8.push(g.Jo("yt-remote-cast2-receiver-resumed",function(){l5("yt-remote-receiver-resumed","cast-selector-receiver")})),T8.push(g.Jo("yt-remote-cast2-session-change",Iqa)),T8.push(g.Jo("yt-remote-connection-change",function(m){m?j8(R8(),"YouTube TV"):V8()||(j8(null,null),f8())})),a=W8(),b.isAuto&&(a.id+="#dial"),g.rp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),S8(" -- with channel params: "+
g.zj(a)),Jqa(a),c.start(),R8()||Kqa())},Mqa=function(){var a=X8();
d8()&&g.by("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},X8=function(){var a=Q8().Sc.$_gos();
var b=Y8();b&&Z8()&&(v5(a,b)||a.push(b));return Vpa(a)},$8=function(){var a=Nqa();
!a&&d8()&&e8()&&(a={key:"cast-selector-receiver",name:e8()});return a},Nqa=function(){var a=X8(),b=Y8();
b||(b=V8());return g.Ya(a,function(c){return b&&p5(b,c.key)?!0:!1})},Y8=function(){var a=R8();
if(!a)return null;var b=Q8().Kd();return w5(b,a)},Iqa=function(a){S8("remote.onCastSessionChange_: "+s5(a));
if(a){var b=Y8();b&&b.id==a.id?j8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){h8()?a8().stopSession():Y7("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},S8=function(a){k7("remote",a)},Q8=function(){if(!e9){var a=g.w("yt.mdx.remote.screenService_");
e9=a?new N8(a):null}return e9},R8=function(){return g.w("yt.mdx.remote.currentScreenId_")},f9=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Oqa=function(){return g.w("yt.mdx.remote.connectData_")},U8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.w("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
U8(null);a||f9("");g.Ga("yt.mdx.remote.connection_",a,void 0);P8&&((0,g.z)(P8,function(c){c(a)}),P8.length=0);
b&&!a?l5("yt-remote-connection-change",!1):!b&&a&&l5("yt-remote-connection-change",!0)},V8=function(){var a=g.jL();
if(!a)return null;var b=Q8().Kd();return w5(b,a)},b9=function(a,b){Y8()&&Y8();
if(g9)h9=a;else{f9(a.id);var c=new C8(O8,a,W8());c.connect(b,Oqa());c.subscribe("beforeDisconnect",function(d){l5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)}},Kqa=function(){var a=V8();
a?(S8("Resume connection to: "+s5(a)),b9(a,0)):(F5(),f8(),S8("Skipping connecting because no session screen found."))},Hqa=function(){var a=W8();
if(g.Zb(a)){a=A5();var b=g.by("yt-remote-session-name")||"",c=g.by("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},W8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Jqa=function(a){a?(g.ay("yt-remote-session-app",a.app),g.ay("yt-remote-session-name",a.name)):(m5("yt-remote-session-app"),m5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.E.call(this);
this.u=a;this.i=b;this.l=new g.Qs(this);g.H(this,this.l);this.l.J(b,"onCaptionsTrackListChanged",this.eI);this.l.J(b,"captionschanged",this.eH);this.l.J(b,"captionssettingschanged",this.uz);this.l.J(b,"videoplayerreset",this.dn);this.l.J(b,"mdxautoplaycancel",this.eB);this.P=this.l.J(b,"onVolumeChange",this.Px);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.ey,this);c.subscribe("remotePlayerChange",this.dk,this);c.subscribe("remoteQueueChange",this.dn,this);c.subscribe("autoplayUpNext",this.Fx,
this);c.subscribe("previousNextChange",this.ay,this);c.subscribe("nowAutoplaying",this.Wx,this);c.subscribe("autoplayDismissed",this.Ex,this);this.suggestion=null;this.D=new g.Ct(64);this.o=new g.I(this.rz,500,this);g.H(this,this.o);this.w=new g.I(this.sz,1E3,this);g.H(this,this.w);this.I=new O5(this.JL,0,this);g.H(this,this.I);this.B={};this.R=new g.I(this.Tz,1E3,this);g.H(this,this.R);this.G=new g.jl(this.BE,1E3,this);g.H(this,this.G);this.M=g.Ia;this.uz();this.dn();this.dk()},j9=function(a,b){var c=
a.u,d=a.i.getVideoData().lengthSeconds;
c.R=b||0;c.player.N("progresssync",b,d)},Pqa=function(a){j9(a,0);
a.o.stop();k9(a,new g.Ct(64))},m9=function(a,b){if(l9(a)&&!a.C){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.iz(a.i.getVideoData(1).videoId,c);a.B=u8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Qa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.De,h5(c));k9(a,new g.Ct(1))},Qqa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{RP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.C=!1):(a.i.loadModule("captions"),a.C=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return u8(a.g).videoId==a.i.getVideoData(1).videoId},k9=function(a,b){a.w.stop();
var c=a.D;if(!g.It(c,b)){var d=g.R(b,2);d!=g.R(a.D,2)&&g.lS(a.i.app,d);a.D=b;Rqa(a.u,c,b)}},o9=function(){g.T.call(this,{A:"div",
F:"ytp-mdx-popup-dialog",K:{role:"dialog"},H:[{A:"div",F:"ytp-mdx-popup-dialog-inner-content",H:[{A:"div",F:"ytp-mdx-popup-title",T:"You're signed out"},{A:"div",F:"ytp-mdx-popup-description",T:"Videos that you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{A:"div",F:"ytp-mdx-privacy-popup-buttons",H:[{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"Cancel"},{A:"button",U:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],T:"Confirm"}]}]}]});this.l=new g.pL(this,250);g.H(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.J(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.J(this.u,"click",this.w)},p9=function(a){g.T.call(this,{A:"div",
F:"ytp-remote",H:[{A:"div",F:"ytp-remote-display-status",H:[{A:"div",F:"ytp-remote-display-status-icon",H:[g.rL()]},{A:"div",F:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.pL(this,250);g.H(this,this.l);this.o=a;this.J(a,"presentingplayerstatechange",this.u);Sqa(this,g.lK(a))},Sqa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.R(b,128)?g.WL("Error on $RECEIVER_NAME",c):g.Jt(b)||g.R(b,4)?g.WL("Playing on $RECEIVER_NAME",c):g.WL("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.SN.call(this,"Play on",0,a,b);
this.l=a;this.B={};this.J(a,"onMdxReceiversChange",this.I);this.J(a,"presentingplayerstatechange",this.I);this.I()},r9=function(a){g.aP.call(this,a);
this.i={key:u5(),name:"This computer"};this.u=null;this.o=[];this.M=this.g=null;this.G=[this.i];this.l=this.i;this.B=new g.Ct(64);this.R=0;this.D=-1;this.w=null;if(!g.fz(this.player.L())){a=this.player;var b=g.RC(a);b&&(b=b.Km())&&(b=new q9(a,b),g.H(this,b));b=new p9(a);g.H(this,b);g.DK(a,b.element,4);this.w=new o9;g.H(this,this.w);g.DK(a,this.w.element,4);this.I=!!V8()}this.C=null},s9=function(a){a.C&&(a.player.removeEventListener("presentingplayerstatechange",a.C),a.C=null)},Rqa=function(a,b,c){a.B=
c;
a.player.N("presentingplayerstatechange",new g.hD(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)a9();
else{var c;(c=!g.P(a.player.L().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.uo("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.uo("SESSION_INDEX")&&!g.uo("LOGGED_IN")))||a.I||!a.w);if(c?0:"WEB"==a.player.L().deviceParams.c||"WEB_EMBEDDED_PLAYER"==a.player.L().deviceParams.c)g.Jt(g.lK(a.player))?a.player.pauseVideo():(a.C=(0,g.x)(a.HK,a),a.player.addEventListener("presentingplayerstatechange",a.C)),a.w&&a.w.l.show(),Z8()||(g9=!0);a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ra(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.De,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=h5(c))&&(d.locationInfo=c);c=d}else c=null;S8("Connecting to: "+g.zj(b));"cast-selector-receiver"==b.key?(U8(c||null),h8()?a8().setLaunchParams(c||null):Y7("setLaunchParams called before ready.")):
!c&&d9()&&R8()==b.key?l5("yt-remote-connection-change",!0):(a9(),U8(c||null),c=Q8().Kd(),(c=w5(c,b.key))&&b9(c,1))}},h6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},g6={"'":"\\'"},Tqa={},Tpa={HM:"atp",dP:"ska",SO:"que",uO:"mus",cP:"sus",IN:"dsp",ZO:"seq"};
n5.prototype.Rf=function(){var a=new n5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var G5,z5="",$pa=I5("loadCastFramework")||I5("loadCastApplicationFramework"),vqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ta(O5,g.E);g.h=O5.prototype;g.h.YB=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.A)()+this.Tc:this.za=g.hl(this.u,this.Tc)};
g.h.stop=function(){this.za&&(g.u.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.w.apply(null,this.o)))};
g.h.V=function(){this.stop();O5.xb.V.call(this)};
g.h.ZB=function(){this.l?(this.za=g.hl(this.u,this.l-(0,g.A)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.w.apply(null,this.o)))};Q5.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
Q5.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};R5.prototype.g=null;R5.prototype.getOptions=function(){var a;(a=this.g)||(a={},T5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Ta(S5,R5);u9=new S5;g.h=V5.prototype;g.h.Mg=null;g.h.oe=!1;g.h.Hi=null;g.h.ls=null;g.h.si=null;g.h.Lh=null;g.h.Lf=null;g.h.qg=null;g.h.fh=null;g.h.uc=null;g.h.Gk=0;g.h.ue=null;g.h.Pn=null;g.h.ag=null;g.h.uj=-1;g.h.dz=!0;g.h.Ag=!1;g.h.zp=0;g.h.kn=null;var b6={},$5={};g.h=V5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.TK=function(a){a=a.target;var b=this.kn;b&&3==y6(a)?b.Vl():this.bA(a)};
g.h.bA=function(a){try{if(a==this.uc)a:{var b=y6(this.uc),c=this.uc.w,d=this.uc.getStatus();if(g.Jd&&!g.nd(10)||g.Ld&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bg&&!C6(this.uc))break a;this.Ag||4!=b||7==c||(8==c||0>=d?this.g.ne(3):this.g.ne(2));l6(this);var e=this.uc.getStatus();this.uj=e;var f=C6(this.uc);(this.oe=200==e)?(4==b&&d6(this),this.u?(f6(this,b,f),g.bg&&this.oe&&3==b&&(this.ba.ea(this.i,"tick",this.NK),this.i.start())):c6(this,f),this.oe&&!this.Ag&&(4==b?this.g.an(this):(this.oe=
!1,Z5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ag=3,a6(13)):(this.ag=0,a6(14)),d6(this),e6(this))}}catch(k){this.uc&&C6(this.uc)}finally{}};
g.h.NK=function(){var a=y6(this.uc),b=C6(this.uc);this.Gk<b.length&&(l6(this),f6(this,a,b),this.oe&&4!=a&&Z5(this))};
g.h.jK=function(a){k6((0,g.x)(this.iK,this,a),0)};
g.h.iK=function(a){this.Ag||(l6(this),c6(this,a),Z5(this))};
g.h.ly=function(a){k6((0,g.x)(this.hK,this,a),0)};
g.h.hK=function(a){this.Ag||(d6(this),this.oe=a,this.g.an(this),this.g.ne(4))};
g.h.cancel=function(){this.Ag=!0;d6(this)};
g.h.rK=function(){this.Hi=null;var a=(0,g.A)();0<=a-this.ls?(2!=this.Lh&&this.g.ne(3),d6(this),this.ag=2,a6(18),e6(this)):j6(this,this.ls-a)};
g.h.getLastError=function(){return this.ag};g.h=p6.prototype;g.h.xp=null;g.h.Ad=null;g.h.ln=!1;g.h.ev=null;g.h.Hl=null;g.h.Yp=null;g.h.yp=null;g.h.be=null;g.h.sf=-1;g.h.tj=null;g.h.Ri=null;g.h.connect=function(a){this.yp=a;a=q6(this.g,null,this.yp);a6(3);this.ev=(0,g.A)();var b=this.g.C;null!=b?(this.tj=b[0],(this.Ri=b[1])?(this.be=1,r6(this)):(this.be=2,t6(this))):(g5(a,"MODE","init"),this.Ad=new V5(this,void 0,void 0,void 0),this.Ad.Mg=this.xp,Y5(this.Ad,a,!1,null,!0),this.be=0)};
g.h.fB=function(a){if(a)this.be=2,t6(this);else{a6(4);var b=this.g;b.Ae=b.Qf.sf;W6(b,9)}a&&this.ne(2)};
g.h.To=function(a){return this.g.To(a)};
g.h.abort=function(){this.Ad&&(this.Ad.cancel(),this.Ad=null);this.sf=-1};
g.h.dv=function(){return!1};
g.h.fy=function(a,b){this.sf=a.uj;if(0==this.be)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ae=this.sf;W6(c,2);return}this.tj=c[0];this.Ri=c[1]}else c=this.g,c.Ae=this.sf,W6(c,2);else if(2==this.be)if(this.ln)a6(7),this.Yp=(0,g.A)();else if("11111"==b){if(a6(6),this.ln=!0,this.Hl=(0,g.A)(),c=this.Hl-this.ev,!g.Jd||g.nd(10)||500>c)this.sf=200,this.Ad.cancel(),a6(12),s6(this.g,this,!0)}else a6(8),this.Hl=this.Yp=(0,g.A)(),this.ln=!1};
g.h.an=function(){this.sf=this.Ad.uj;if(this.Ad.oe)0==this.be?this.Ri?(this.be=1,r6(this)):(this.be=2,t6(this)):2==this.be&&((!g.Jd||g.nd(10)?!this.ln:200>this.Yp-this.Hl)?(a6(11),s6(this.g,this,!1)):(a6(12),s6(this.g,this,!0)));else{0==this.be?a6(9):2==this.be&&a6(10);var a=this.g;this.Ad.getLastError();a.Ae=this.sf;W6(a,2)}};
g.h.uk=function(){return this.g.uk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ne=function(a){this.g.ne(a)};g.Ta(u6,g.wk);var eqa=/^https?$/i,Uqa=["POST","PUT"];g.h=u6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.o="";this.w=0;this.W=b;this.P=!1;this.l=!0;this.g=this.M?U5(this.M):U5(u9);this.R=this.M?this.M.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.x)(this.fv,this);try{k5(z6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){k5(z6(this,"Error opening Xhr: "+f.message));x6(this,f);return}a=c||"";
var e=this.headers.clone();d&&Opa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Yd(),dqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.ab(Uqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{B6(this),0<this.B&&(this.I=cqa(this.g),k5(z6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.B,this.g.ontimeout=(0,g.x)(this.gv,this)):this.G=g.hl(this.gv,this.B,this)),k5(z6(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){k5(z6(this,"Send error: "+f.message)),x6(this,f)}};
g.h.gv=function(){"undefined"!=typeof g.yZ&&this.g&&(this.o="Timed out after "+this.B+"ms, aborting",this.w=8,z6(this,this.o),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(z6(this,"Aborting"),this.l=!1,this.u=!0,this.g.abort(),this.u=!1,this.w=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),w6(this))};
g.h.V=function(){this.g&&(this.l&&(this.l=!1,this.u=!0,this.g.abort(),this.u=!1),w6(this,!0));u6.xb.V.call(this)};
g.h.fv=function(){this.fa()||(this.aa||this.C||this.u?A6(this):this.iJ())};
g.h.iJ=function(){A6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<y6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.o?this.o:String(this.o)};g.h=D6.prototype;g.h.dj=null;g.h.td=null;g.h.Qb=null;g.h.wp=null;g.h.Jl=null;g.h.Et=null;g.h.Wl=null;g.h.Yj=0;g.h.yG=0;g.h.Qc=null;g.h.Wf=null;g.h.ff=null;g.h.Fg=null;g.h.Qf=null;g.h.Nn=null;g.h.Yh=-1;g.h.Rv=-1;g.h.Ae=-1;g.h.Eh=0;g.h.yh=0;g.h.Bg=8;var X6=new g.wk;g.Ta(E6,g.Zj);g.Ta(F6,g.Zj);g.Ta(G6,g.Zj);g.h=D6.prototype;g.h.connect=function(a,b,c,d,e){a6(0);this.wp=b;this.dj=c||{};d&&void 0!==e&&(this.dj.OSID=d,this.dj.OAID=e);this.w?(k6((0,g.x)(this.Yt,this,a),100),M6(this)):this.Yt(a)};
g.h.Yt=function(a){this.Qf=new p6(this);this.Qf.xp=null;this.Qf.i=this.u;this.Qf.connect(a)};
g.h.dv=function(){return 0==this.g};
g.h.ky=function(a){this.Wf=null;R6(this,a)};
g.h.jy=function(){this.ff=null;this.Qb=new V5(this,this.l,"rpc",this.B);this.Qb.Mg=null;this.Qb.zp=0;var a=this.Et.clone();e5(a,"RID","rpc");e5(a,"SID",this.l);e5(a,"CI",this.Nn?"0":"1");e5(a,"AID",this.Yh);I6(this,a);if(!g.Jd||g.nd(10))e5(a,"TYPE","xmlhttp"),Y5(this.Qb,a,!0,this.Wl,!1);else{e5(a,"TYPE","html");var b=this.Qb,c=!!this.Wl;b.Lh=3;b.Lf=f5(a.clone());i6(b,c)}};
g.h.fy=function(a,b){if(0!=this.g&&(this.Qb==a||this.td==a))if(this.Ae=a.uj,this.td==a&&3==this.g)if(7<this.Bg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.ff){if(this.Qb)if(this.Qb.si+3E3<this.td.si)N6(this),this.Qb.cancel(),this.Qb=null;else break a;U6(this);a6(19)}}else this.Rv=c[1],0<this.Rv-this.Yh&&37500>c[2]&&this.Nn&&0==this.yh&&!this.Fg&&(this.Fg=k6((0,g.x)(this.aH,this),6E3));else W6(this,11)}else b!=Tqa.gN.g&&W6(this,11);else if(this.Qb==a&&
N6(this),!g.yb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Wl=e[2],e=e[3],null!=e?this.Bg=e:this.Bg=6,this.g=3,this.Qc&&this.Qc.St(),this.Et=q6(this,this.uk()?this.Wl:null,this.wp),S6(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.Qc&&this.Qc.Rt(e),this.yh=0)}}};
g.h.aH=function(){null!=this.Fg&&(this.Fg=null,this.Qb.cancel(),this.Qb=null,U6(this),a6(20))};
g.h.an=function(a){if(this.Qb==a){N6(this);this.Qb=null;var b=2}else if(this.td==a)this.td=null,b=1;else return;this.Ae=a.uj;if(0!=this.g)if(a.oe)1==b?(b=(0,g.A)()-a.si,X6.dispatchEvent(new F6(X6,a.fh?a.fh.length:0,b,this.Eh)),L6(this),this.o.length=0):S6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ae)){if(d=1==b)this.td||this.Wf||1==this.g||2<=this.Eh?d=!1:(this.Wf=k6((0,g.x)(this.ky,this,a),T6(this,this.Eh)),this.Eh++,d=!0);d=!(d||2==b&&U6(this))}if(d)switch(c){case 1:W6(this,
5);break;case 4:W6(this,10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.zB=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.AL=function(a){a?a6(2):(a6(1),V6(this,8))};
g.h.To=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new u6;a.S=!1;return a};
g.h.isActive=function(){return!!this.Qc&&this.Qc.isActive(this)};
g.h.ne=function(a){X6.dispatchEvent(new G6(X6,a))};
g.h.uk=function(){return!(!g.Jd||g.nd(10))};
g.h=Y6.prototype;g.h.St=function(){};
g.h.Rt=function(){};
g.h.Qt=function(){};
g.h.Mo=function(){};
g.h.Fu=function(){return{}};
g.h.isActive=function(){return!0};g.h=Z6.prototype;g.h.isEmpty=function(){return g.bb(this.g)&&g.bb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.una)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.wd=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Ta($6,g.E);g.h=$6.prototype;g.h.aK=function(){this.Tc=Math.min(3E5,2*this.Tc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Tc+15E3*Math.random();g.bn(this.g,a);this.i=(0,g.A)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Tc=5E3};g.Ta(a7,Y6);g.h=a7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Af=function(a){return this.l.Ng(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.bb||(this.bb=!0,g.Ci(this.l),b7(this),g.Ci(this.i),this.i=null)};
g.h.fa=function(){return this.bb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.D="";this.i.stop();this.u=a||null;this.o=b||0;a=this.G+"/test";b=this.G+"/bind";var d=new D6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Qc=null);d.Qc=this;this.g=d;e?this.g.connect(a,b,this.w,e.l,e.Yh):c?this.g.connect(a,b,this.w,c.sessionId,c.arrayId):this.g.connect(a,b,this.w)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):c7(this)&&O6(this.g,c)};
g.h.St=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)O6(this.g,a[b])}this.N("handlerOpened")};
g.h.Qt=function(a){var b=2==a&&401==this.g.Ae;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Mo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Fu=function(){var a={v:2};this.D&&(a.gsessionid=this.D);0!=this.o&&(a.ui=""+this.o);0!=this.C&&(a.ui=""+this.C);this.u&&g.ec(a,this.u);return a};
g.h.Rt=function(a){"S"==a[0]?this.D=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),K6(this.g)):this.N("handlerMessage",new gqa(a[0],a[1]))};
g.h.dL=function(){this.i.isActive();var a=this.g,b=0;a.Qb&&b++;a.td&&b++;0==b&&this.connect(this.u,this.o)};d7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
d7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
d7.prototype.u=function(a){a(Error("request timed out"))};var mqa=(0,g.A)(),i7=null,m7=Array(50),l7=-1,n7=!1;g.Ta(o7,g.O);o7.prototype.Kd=function(){return this.g};
o7.prototype.contains=function(a){return!!v5(this.g,a)};
o7.prototype.get=function(a){return a?w5(this.g,a):null};
o7.prototype.info=function(a){k7(this.B,a)};g.r(q7,g.O);g.h=q7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.fA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Eo(this.za),this.za=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.fA=function(){this.za=NaN;this.g=g.Ap(e7(this.w,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.cM,this),onError:(0,g.x)(this.bM,this),Nd:(0,g.x)(this.dM,this)})};
g.h.cM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new o5(c))};
g.h.bM=function(a){this.g=null;a.status&&404==a.status?this.i>=Vqa.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Vqa[this.i],this.za=g.Co((0,g.x)(this.fA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.dM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var Vqa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(s7,o7);g.h=s7.prototype;g.h.start=function(){r7(this)&&this.N("screenChange");!g.by("yt-remote-lounge-token-expiration")&&t7(this);g.Eo(this.i);this.i=g.Co((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){r7(this);p7(this,a);u7(this,!1);this.N("screenChange");b(a);a.token||t7(this)};
g.h.remove=function(a,b){var c=r7(this);oqa(this,a)&&(u7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Jn=function(a,b,c,d){var e=r7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,u7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.V=function(){g.Eo(this.i);s7.xb.V.call(this)};
g.h.jC=function(a){r7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}u7(this,!b);b&&k7(this.B,"Missed "+b+" lounge tokens.")};
g.h.iC=function(a){k7(this.B,"Requesting lounge tokens failed: "+a)};g.r(w7,g.O);g.h=w7.prototype;g.h.start=function(){var a=parseInt(g.by("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.A)()-144E5<a?0:a)?z7(this):(this.o=(0,g.A)()+3E5,g.ay("yt-remote-fast-check-period",this.o),this.vr())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){v7("Updating availability on schedule.");var a=this.w(),b=g.Nb(this.g,function(c,d){return c&&!!w5(a,d)},this);
y7(this,b)};
g.h.V=function(){g.Eo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.vr=function(){g.Eo(this.l);this.l=NaN;this.i&&this.i.abort();var a=A7(this);if(i5(a)){var b=e7(this.u,"/pairing/get_screen_availability");this.i=f7(this.u,b,{lounge_token:g.Tb(a).join(",")},(0,g.x)(this.EJ,this,a),(0,g.x)(this.DJ,this))}else y7(this,{}),z7(this)};
g.h.EJ=function(a,b){this.i=null;var c=g.Tb(A7(this));if(g.sb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;y7(this,d);z7(this)}else this.Kb("Changing Screen set during request."),this.vr()};
g.h.DJ=function(a){this.Kb("Screen availability failed: "+a);this.i=null;z7(this)};
g.h.Kb=function(a){k7("OnlineScreenService",a)};g.Ta(B7,o7);g.h=B7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Jn=function(a,b,c,d){this.l.contains(a)?this.l.Jn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.B,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.g:g.gb(this.g,(0,g.Wd)(this.o,function(b){return!this.contains(b)},this))};
g.h.gA=function(){return(0,g.Wd)(this.Kd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.hA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new q7(this.w,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ci(f);d(C7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ci(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.fM=function(a,b,c,d){g.Ap(e7(this.w,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new o5(f.screen||{});if(!k.name||E7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);E7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(C7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ci(this.l);g.Ci(this.i);B7.xb.V.call(this)};
g.h.qC=function(){F7(this);this.N("screenChange");this.i.update()};
B7.prototype.dispose=B7.prototype.dispose;g.Ta(H7,g.O);g.h=H7.prototype;g.h.cn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Md=function(a){this.fa()||(a&&I7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){k7(this.R,a)};
g.h.jA=function(){return null};
g.h.Dr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){I7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Dr("");H7.xb.V.call(this)};g.Ta(K7,H7);g.h=K7.prototype;g.h.Cr=function(a){if(this.g){if(this.g==a)return;I7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.w);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.w);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);sqa(this)};
g.h.Zh=function(a){this.info("launchWithParams no-op for Cast: "+g.zj(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.Dr=g.Ia;g.h.V=function(){this.info("disposeInternal");g.Eo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.w),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;K7.xb.V.call(this)};
g.h.CK=function(a,b){if(!this.fa())if(b){var c=P5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.zj(c));switch(d){case "mdxSessionStatus":J7(this,c.screenId);break;default:I7(this,"Unknown youtube message: "+d)}}else I7(this,"Unable to parse message.")}else I7(this,"No data in message.")};
g.h.Yu=function(a,b,c,d){D7(this.D,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(I7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Co((0,g.x)(this.Yu,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.jA=function(){return this.g};
g.h.gM=function(a){this.fa()||a||(I7(this,"Cast session died."),this.Md())};g.Ta(L7,H7);g.h=L7.prototype;g.h.Cr=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.Zh=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ia;g.Eo(this.w);this.o?this.o.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.V=function(){this.g();this.g=g.Ia;g.Eo(this.w);this.o&&this.o.removeUpdateListener(this.I);this.o=null;L7.xb.V.call(this)};
g.h.jM=function(a){this.fa()||a||(I7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Md())};
g.h.Kp=function(a){this.G=u5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,N7(this));a(b);M7(this)}else this.B=(0,g.x)(function(){g.Eo(this.w);this.B=g.Ia;this.w=NaN;var c=new chrome.cast.DialLaunchResponse(!0,N7(this));a(c);M7(this)},this),this.w=g.Co((0,g.x)(function(){this.B()},this),100)};
g.h.LC=function(a,b,c){D7(this.D,this.C.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.cn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Kp(b,c)},this),(0,g.x)(function(d){I7(this,"Failed to get DIAL screen: "+d);
this.Kp(b,c)},this))};g.Ta(O7,H7);O7.prototype.stop=function(){this.Md()};
O7.prototype.Cr=g.Ia;O7.prototype.Zh=function(){g.Eo(this.g);this.g=NaN;var a=w5(this.D.Kd(),this.i.label);a?this.cn(a):this.Md(Error("No such screen"))};
O7.prototype.V=function(){g.Eo(this.g);this.g=NaN;O7.xb.V.call(this)};g.Ta(P7,g.O);g.h=P7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.C||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.nJ,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.hy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.zH,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),jqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.iA,this)),this.l=U7(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(k){this.Kb("Failed to set initial custom receivers: "+g.zj(k))},this)),this.N("yt-remote-cast2-availability-change",S7(this)),b(!0))},this),(0,g.x)(function(k){this.Kb("Failed to initialize API: "+g.zj(k));
b(!1)},this))};
g.h.lL=function(a,b){R7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)R7("Unsetting old screen status: "+this.g.i.friendlyName),T7(this,null)}if(a&&b){if(!this.g){c=w5(this.i.Kd(),a);if(!c){R7("setConnectedScreenStatus: Unknown screen.");return}var d=Q7(this,c);d||(R7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.x)(function(e){this.Kb("Failed to set initial custom receivers: "+g.zj(e))},this)));
R7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);T7(this,new O7(this.i,d),!0)}this.g.Dr(b)}else R7("setConnectedScreenStatus: no screen.")};
g.h.mL=function(a){this.fa()?this.Kb("Setting connection data on disposed cast v2"):this.g?this.g.Zh(a):this.Kb("Setting connection data without a session")};
g.h.iM=function(){this.fa()?this.Kb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),T7(this,null)):R7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.hy,this),(0,g.x)(this.KJ,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.iA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],g7);g.Ci(this.g);P7.xb.V.call(this)};
g.h.Kb=function(a){k7("Controller",a)};
g.h.iy=function(a,b){this.g==a&&(b||T7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.jJ=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),R7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)R7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{R7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:T7(this,
new O7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:T7(this,new L7(this.i,a,this.w));break;case chrome.cast.ReceiverType.CAST:T7(this,new K7(this.i,a));break;default:this.Kb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Kb("Stopping receiver w/o session: "+a.friendlyName)}else this.Kb("onReceiverAction_ called without receiver.")};
g.h.zH=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Kb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return R7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);T7(this,new L7(this.i,b,this.w))}b=this.g;b.C=a;return b.C.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.LC,b,(b.C.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Kp,b))};
g.h.hy=function(a){if(!this.fa()){R7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)R7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),T7(this,new K7(this.i,b),!0);else{this.Kb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=w5(this.i.Kd(),c.label);d&&p5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(R7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ci(this.g),this.g=new K7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.iy,this,this.g)),this.g.Zh(null));this.g.Cr(a)}}};
g.h.hM=function(){return this.g?this.g.jA():null};
g.h.KJ=function(a){this.fa()||(this.Kb("Failed to estabilish a session: "+g.zj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&T7(this,null))};
g.h.nJ=function(a){R7("Receiver availability updated: "+a);if(!this.fa()){var b=S7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;S7(this)!=b&&this.N("yt-remote-cast2-availability-change",S7(this))}};
g.h.iA=function(){this.fa()||(this.l=U7(this),R7("Updating custom receivers: "+g.zj(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(){this.Kb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",S7(this)))};
P7.prototype.setLaunchParams=P7.prototype.mL;P7.prototype.setConnectedScreenStatus=P7.prototype.lL;P7.prototype.stopSession=P7.prototype.iM;P7.prototype.getCastSession=P7.prototype.hM;P7.prototype.requestSession=P7.prototype.requestSession;P7.prototype.init=P7.prototype.init;P7.prototype.dispose=P7.prototype.dispose;var c8=[];k8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";l8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Be=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.w=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.D=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
k8.prototype.isAdPlaying=function(){return 1081==this.playerState};
k8.prototype.getDuration=function(){return this.u?this.C+m8(this):this.C};
k8.prototype.clone=function(){return new k8(q8(this))};g.r(t8,g.O);g.h=t8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,B8(this,"play")):z8(this,"play"),y8(this,1,o8(u8(this))),this.N("remotePlayerChange")):w8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,B8(this,"pause")):z8(this,"pause"),y8(this,2,o8(u8(this))),this.N("remotePlayerChange")):w8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=u8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,B8(this,"seekTo",{newTime:a}))}else z8(this,"seekTo",{newTime:a});y8(this,3,a);this.N("remotePlayerChange")}else w8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,B8(this,"stopVideo")):z8(this,"stopVideo");var a=u8(this);a.index=-1;a.videoId="";l8(a);x8(this,a);this.N("remotePlayerChange")}else w8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=u8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Kb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Kb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);z8(this,"setVolume",e)}c.muted=b;c.volume=a;x8(this,c)}else w8(this,g.Ra(this.setVolume,a,b))};
g.h.iz=function(a,b){if(1==this.g){var c=u8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.zj(b.style),g.ec(d,c.g));z8(this,"setSubtitlesTrack",d);x8(this,c)}else w8(this,g.Ra(this.iz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();z8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=u8(this);d.audioTrackId=c;x8(this,d)}else w8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=u8(this);c=c||0;var m={videoId:a,currentIndex:c};p8(l,a,c);g.Ca(b)&&(n8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.zj(k));z8(this,"setPlaylist",m);d||x8(this,l)};
g.h.eA=function(a,b){if(1==this.g){if(a&&b){var c=u8(this);p8(c,a,b);x8(this,c)}z8(this,"previous")}else w8(this,g.Ra(this.eA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=u8(this);p8(c,a,b);x8(this,c)}z8(this,"next")}else w8(this,g.Ra(this.nextVideo,a,b))};
g.h.hu=function(){1==this.g?z8(this,"dismissAutoplay"):w8(this,this.hu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){v8(this);this.o=null;this.u.clear();s8(this,null);g.O.prototype.V.call(this)};
g.h.rs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,g.bb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.gJ=function(a,b){this.N(a,b)};
g.h.gH=function(a){if(!a)this.bk(null),s8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=u8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,x8(this,b)}};
g.h.bk=function(a){k7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.C);if(this.i=a)this.i.addUpdateListener(this.C),A8(this),this.N("remotePlayerChange")};
g.h.fH=function(a){a?(A8(this),this.N("remotePlayerChange")):this.bk(null)};
g.h.sH=function(){var a=g8();a&&s8(this,a)};
g.h.Kb=function(a){k7("CP",a)};g.r(C8,g.O);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Na.listId=c);this.Na.videoId=d;this.Na.index=k||0;this.Na.state=3;n8(this.Na,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.zj(l));this.g.connect({method:"setPlaylist",
params:g.zj(l)},a,C5())}else D8("Connecting without params"),this.g.connect({},a,C5());zqa(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),E8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){F8(this);H8(this);G8(this);g.Eo(this.B);this.B=NaN;g.Eo(this.C);this.C=NaN;this.l=null;g.$q(this.R);this.R.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.w=this.i=this.Na=this.g=null};
g.h.cC=function(){this.Ch(2)};
g.h.kH=function(){D8("Channel opened");this.I&&(this.I=!1,G8(this),this.G=g.Co((0,g.x)(function(){D8("Timing out waiting for a screen.");this.Ch(1)},this),15E3));
Ypa(hqa(this.g),this.M)};
g.h.hH=function(){D8("Channel closed");isNaN(this.u)?F5(!0):F5();this.dispose()};
g.h.iH=function(a){F5();isNaN(this.nj())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,D8("Channel error: "+a+" with reconnection in "+this.nj()+" ms"),E8(this,2))};
g.h.jH=function(a){a.params?D8("Received: action="+a.action+", params="+g.zj(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=P5(a.params.devices);this.i=(0,g.fe)(a,function(c){return new n5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
K8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
K8(this,!1);break;case "remoteConnected":var b=new n5(P5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||Lpa(this.i,b);
break;case "remoteDisconnected":b=new n5(P5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":L8(this,a);break;case "nowPlaying":Cqa(this,a);break;case "onStateChange":M8(this,a);break;case "onAdStateChange":Dqa(this,a);break;case "onVolumeChanged":Eqa(this,a);break;case "onSubtitlesTrackChanged":Bqa(this,a);break;case "nowAutoplaying":Fqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.w=a.params.videoId||null;this.N("autoplayUpNext",this.w);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Gqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.aL=function(){if(this.l){var a=this.l;this.l=null;this.Na.videoId!=a&&I8(this,"getNowPlaying")}};
g.h.SB=function(){var a=3;this.fa()||(a=0,isNaN(this.nj())?c7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Ch=function(a){D8("Disconnecting with "+a);F8(this);this.N("beforeDisconnect",a);1==a&&F5();b7(this.g,a);this.dispose()};
g.h.RB=function(){var a=this.Na;this.l&&(a=this.Na.clone(),p8(a,this.l,a.index));return q8(a)};
g.h.nL=function(a){var b=new k8(a);b.videoId&&b.videoId!=this.Na.videoId&&(this.l=b.videoId,g.Eo(this.B),this.B=g.Co((0,g.x)(this.aL,this),5E3));var c=[];this.Na.listId==b.listId&&this.Na.videoId==b.videoId&&this.Na.index==b.index||c.push("remoteQueueChange");this.Na.playerState==b.playerState&&this.Na.volume==b.volume&&this.Na.muted==b.muted&&o8(this.Na)==o8(b)&&g.zj(this.Na.g)==g.zj(b.g)||c.push("remotePlayerChange");this.Na.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Wu=function(){var a=this.g.w.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.nj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.A)():NaN};
g.h.LB=function(){return this.o||"UNSUPPORTED"};
g.h.MB=function(){return this.w||""};
g.h.aM=function(){if(!isNaN(this.nj())){var a=this.g.i;g.cn(a.g);a.start()}};
g.h.iL=function(a,b){I8(this,a,b);J8(this)};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Af;C8.prototype.getProxyState=C8.prototype.SB;C8.prototype.disconnect=C8.prototype.Ch;C8.prototype.getPlayerContextData=C8.prototype.RB;C8.prototype.setPlayerContextData=C8.prototype.nL;C8.prototype.getOtherConnectedRemoteId=C8.prototype.Wu;C8.prototype.getReconnectTimeout=C8.prototype.nj;C8.prototype.getAutoplayMode=C8.prototype.LB;C8.prototype.getAutoplayVideoId=C8.prototype.MB;C8.prototype.reconnect=C8.prototype.aM;
C8.prototype.sendMessage=C8.prototype.iL;g.r(N8,o7);g.h=N8.prototype;g.h.Kd=function(a){return this.Sc.$_gs(a)};
g.h.contains=function(a){return!!this.Sc.$_c(a)};
g.h.get=function(a){return this.Sc.$_g(a)};
g.h.start=function(){this.Sc.$_st()};
g.h.add=function(a,b,c){this.Sc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Sc.$_r(a,b,c)};
g.h.Jn=function(a,b,c,d){this.Sc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Sc.$_ubk(this.i[a]);this.i.length=0;this.Sc=null;o7.prototype.V.call(this)};
g.h.eM=function(){this.N("screenChange")};
g.h.JI=function(){this.N("onlineScreenChange")};
B7.prototype.$_st=B7.prototype.start;B7.prototype.$_gspc=B7.prototype.fM;B7.prototype.$_gsppc=B7.prototype.hA;B7.prototype.$_c=B7.prototype.contains;B7.prototype.$_g=B7.prototype.get;B7.prototype.$_a=B7.prototype.add;B7.prototype.$_un=B7.prototype.Jn;B7.prototype.$_r=B7.prototype.remove;B7.prototype.$_gs=B7.prototype.Kd;B7.prototype.$_gos=B7.prototype.gA;B7.prototype.$_s=B7.prototype.subscribe;B7.prototype.$_ubk=B7.prototype.Af;var h9=null,g9=!1,O8=null,P8=null,e9=null,T8=[];g.r(i9,g.E);g.h=i9.prototype;
g.h.V=function(){g.E.prototype.V.call(this);this.o.stop();this.w.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.ey,this);this.g.unsubscribe("remotePlayerChange",this.dk,this);this.g.unsubscribe("remoteQueueChange",this.dn,this);this.g.unsubscribe("autoplayUpNext",this.Fx,this);this.g.unsubscribe("previousNextChange",this.ay,this);this.g.unsubscribe("nowAutoplaying",this.Wx,this);this.g.unsubscribe("autoplayDismissed",this.Ex,this);this.g=this.u=null};
g.h.Bw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!u8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==u8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.G.Vl(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.eH=function(a){this.I.YB(a)};
g.h.JL=function(a){this.Bw("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.uz=function(){var a=this.i.getOption("captions","track");g.Zb(a)||m9(this,a)};
g.h.Px=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.dk,this);var b=Math.round(a.volume);a=!!a.muted;var c=u8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.dk,this)}};
g.h.eI=function(){g.Zb(this.B)||Qqa(this,this.B);this.C=!1};
g.h.ey=function(a,b){this.w.stop();2==b&&this.sz()};
g.h.dk=function(){if(l9(this)){this.o.stop();var a=u8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.D=1;break;case 1082:case 1083:this.u.D=0;break;default:this.u.D=-1}switch(a.playerState){case 1081:case 1:k9(this,new g.Ct(8));this.rz();break;case 1085:case 3:k9(this,new g.Ct(9));break;case 1083:case 0:k9(this,new g.Ct(2));this.G.stop();j9(this,this.i.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.Ct(4));break;case 2:k9(this,new g.Ct(4));j9(this,o8(a));
break;case -1:k9(this,new g.Ct(64));break;case -1E3:k9(this,new g.Ct(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=u8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,Qqa(this,a));a=u8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.Tz()}else Pqa(this)};
g.h.ay=function(){this.i.N("mdxpreviousnextchange")};
g.h.dn=function(){l9(this)||Pqa(this)};
g.h.eB=function(){this.g.hu()};
g.h.Fx=function(a){a&&!g.P(this.i.L().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Ap("/watch_queue_ajax",{method:"GET",od:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.lK,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.lK=function(a,b){var c=new g.LB(this.i.L(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Wx=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Ex=function(){this.i.N("mdxautoplaycanceled")};
g.h.BE=function(a,b){-1==u8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.Tz=function(){if(l9(this)){var a=u8(this.g);this.l.Sa(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.J(this.i,"onVolumeChange",this.Px)}};
g.h.rz=function(){this.o.stop();if(!this.g.fa()){var a=u8(this.g);1==a.playerState&&k9(this,new g.Ct(8));j9(this,o8(a));this.o.start()}};
g.h.sz=function(){this.w.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.w.start()};g.r(o9,g.T);o9.prototype.o=function(){l5("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.w=function(){l5("mdx-privacy-popup-confirm");this.l.hide()};g.r(p9,g.T);p9.prototype.u=function(a){Sqa(this,a.state)};g.r(q9,g.SN);q9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.vb(a,this.w,this),g.UN(this,(0,g.fe)(a,this.w)),a=this.l.getOption("remote","currentReceiver"),this.ee(this.w(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.w=function(a){return a.key};
q9.prototype.me=function(a){return"cast-selector-receiver"==a?"Cast...":this.B[a].name};
q9.prototype.Mc=function(a){g.SN.prototype.Mc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.gb()};g.r(r9,g.aP);g.h=r9.prototype;
g.h.create=function(){Lqa(g.Xy(this.player.L()));this.o.push(g.Jo("yt-remote-before-disconnect",this.bH,this));this.o.push(g.Jo("yt-remote-connection-change",this.oJ,this));this.o.push(g.Jo("yt-remote-receiver-availability-change",this.by,this));this.o.push(g.Jo("yt-remote-auto-connect",this.mJ,this));this.o.push(g.Jo("yt-remote-receiver-resumed",this.lJ,this));this.o.push(g.Jo("mdx-privacy-popup-confirm",this.QK,this));this.o.push(g.Jo("mdx-privacy-popup-cancel",this.PK,this));this.by()};
g.h.load=function(){this.player.cancelPlayback();g.aP.prototype.load.call(this);this.u=new i9(this,this.player,this.g);var a=(a=Oqa())?a.currentTime:0;var b=d9()?new t8(Z8(),void 0):null;0==a&&b&&(a=o8(u8(b)));0!=a&&(this.R=a||0,this.player.N("progresssync",a,void 0));Rqa(this,this.B,this.B);g.rS(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.Di(this.u,this.g);this.g=this.u=null;g.aP.prototype.unload.call(this);g.rS(this.player.app,5);s9(this)};
g.h.V=function(){g.Ko(this.o);g.aP.prototype.V.call(this)};
g.h.Oj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Bw.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.D};
g.h.UB=function(){return this.loaded?this.u.suggestion:null};
g.h.Be=function(){return this.g?u8(this.g).Be:!1};
g.h.hasNext=function(){return this.g?u8(this.g).hasNext:!1};
g.h.getCurrentTime=function(){return this.R};
g.h.getProgressState=function(){var a=u8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.L().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.oc():!a.isAdPlaying()&&this.player.oc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+m8(a):a.l,isAtLiveHead:1>=(a.u?a.i+m8(a):a.i)-this.getCurrentTime(),loaded:a.D,seekableEnd:a.u?a.i+m8(a):a.i,seekableStart:0<a.o?a.o+m8(a):
a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.pE=function(){this.g&&this.g.eA()};
g.h.bH=function(a){1==a&&(this.M=this.g?u8(this.g):null)};
g.h.oJ=function(){var a=d9()?new t8(Z8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.M=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Ci(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.M)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,o8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.by=function(){this.G=[this.i].concat(Mqa());var a=$8()||this.i;t9(this,a);this.player.ha("onMdxReceiversChange")};
g.h.HK=function(a){!this.I&&g.jD(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.mJ=function(){var a=$8();t9(this,a)};
g.h.lJ=function(){this.l=$8()};
g.h.QK=function(){this.I=!0;s9(this);g9=!1;h9&&b9(h9,1);h9=null};
g.h.PK=function(){this.I=!1;s9(this);t9(this,this.i);this.l=this.i;g9=!1;h9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?i8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&i8(),!0):!1}};
g.h.qE=function(){z8(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Se=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.oP.remote=r9;})(_yt_player);
